### ISSUE TITLE
adblock-rs failing with node failure

### ISSUE THREAD

**Issue by jumde** [brave/brave-core-crx-packager#101]
```
10:55:06 Error: Cannot find module '../native'
10:55:06 Require stack:
10:55:06 - /Users/jenkins/jenkins/workspace/ad-block-rust-update/node_modules/adblock-rs/lib/index.js
10:55:06 - /Users/jenkins/jenkins/workspace/ad-block-rust-update/scripts/generateAdBlockRustDataFiles.js
10:55:06     at Function.Module._resolveFilename (internal/modules/cjs/loader.js:794:15)
10:55:06     at Function.Module._load (internal/modules/cjs/loader.js:687:27)
10:55:06     at Module.require (internal/modules/cjs/loader.js:849:19)
10:55:06     at require (internal/modules/cjs/helpers.js:74:18)
10:55:06     at Object.<anonymous> (/Users/jenkins/jenkins/workspace/ad-block-rust-update/node_modules/adblock-rs/lib/index.js:1:17)
10:55:06     at Module._compile (internal/modules/cjs/loader.js:956:30)
10:55:06     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
10:55:06     at Module.load (internal/modules/cjs/loader.js:812:32)
10:55:06     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
10:55:06     at Module.require (internal/modules/cjs/loader.js:849:19) {
10:55:06   code: 'MODULE_NOT_FOUND',
10:55:06   requireStack: [
10:55:06     '/Users/jenkins/jenkins/workspace/ad-block-rust-update/node_modules/adblock-rs/lib/index.js',
10:55:06     '/Users/jenkins/jenkins/workspace/ad-block-rust-update/scripts/generateAdBlockRustDataFiles.js'
10:55:06   ]
10:55:06 }
10:55:06 npm ERR! code ELIFECYCLE
10:55:06 npm ERR! errno 1
```

**Comment by jumde** [comment]
fixed with revert in https-everywhere-builder
