### ISSUE TITLE
Fix `npm ERR! Cannot convert undefined or null to object` from `npm install`

### ISSUE THREAD

**Issue by simonhong** [brave/brave-core-crx-packager#602]
Got this failure while running `npm install`.
As this blocks some CI jobs, `--no-audit` is used for `npm install` as a workaround fix.

```
77 verbose stack TypeError: Cannot convert undefined or null to object
77 verbose stack     at Function.keys (<anonymous>)
77 verbose stack     at Advisory.load (/usr/local/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/advisory.js:109:33)
77 verbose stack     at [calculate] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/metavuln-calculator/lib/index.js:60:14)
77 verbose stack     at async Promise.all (index 0)
77 verbose stack     at async [init] (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:188:9)
77 verbose stack     at async AuditReport.run (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/audit-report.js:109:7)
77 verbose stack     at async Arborist.reify (/usr/local/lib/node_modules/npm/node_modules/@npmcli/arborist/lib/arborist/reify.js:179:24)
77 verbose stack     at async Install.exec (/usr/local/lib/node_modules/npm/lib/commands/install.js:146:5)
77 verbose stack     at async module.exports (/usr/local/lib/node_modules/npm/lib/cli.js:134:5)
78 verbose cwd /Users/simon/Projects/brave/brave-core-crx-packager
79 verbose Darwin 22.4.0
80 verbose node v18.15.0
81 verbose npm  v9.5.0
82 error Cannot convert undefined or null to object
83 verbose exit 1
84 timing npm Completed in 973ms
```

**Comment by antonok-edm** [comment]
Closed <sup>somehow?</sup> by https://github.com/brave/brave-core-crx-packager/pull/605
